apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::005996068962:role/eksctl-eksctl-demo-nodegroup-ng-8-NodeInstanceRole-1KUTLJM5AK8ZS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::005996068962:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-05T09:53:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1503"
  uid: b85e0c65-f641-4f2d-a23a-b97977deb393
